new speech recognition API
charisma-ai/charisma-sdk-unity pull request #21
Opened 2023-08-31 16:39 UTC by RaduDumitriu-Dev

- adds speech recognition
- uses new unified message format
- adds speech recognition configuration class, w/ several paramaters
- at time of writing languageCode and encoding do not seem to produce any results and have been commented out. need clarification on these two during feedback

2023-09-01 08:48 UTC, John-A-J commented on Scripts/Audio.cs
> +        public enum SpeechRecognitionLanguageCode
I think we should not be prescriptive with the language code and just accept any string directly. Different services allow different language codes and may also add or change accepted codes in the future

2023-09-01 08:50 UTC, John-A-J commented on Scripts/Audio.cs
> +                        Logger.LogError("Unknown audio format");
```suggestion
                        Logger.LogError("Unrecognised SpeechRecognitionService");
```

2023-09-01 10:06 UTC, bensalilijames requested changes

2023-09-01 10:06 UTC, bensalilijames commented on Scripts/Events.cs
> +        public int durationInSeconds;
`int` -> `float`

2023-09-01 10:06 UTC, bensalilijames commented on Scripts/Audio.cs
> +        private SpeechRecognitionLanguageCode _languageCode = SpeechRecognitionLanguageCode.EN_GB;
default should be `en-US` to match server

2023-09-01 10:06 UTC, bensalilijames commented on Scripts/Audio.cs
> +        public string Encoding
I don't think we need `Encoding` as we control the microphone implementation so we know what it's going to be

2023-09-01 10:06 UTC, bensalilijames commented on Scripts/Audio.cs
> +    public class SpeechRecognitionOptions
maybe put all the speech recognition stuff into a separate file to avoid cluttering `Audio`

2023-09-04 12:34 UTC, bensalilijames approved these changes
awesome, looks good! 👍

2023-09-04 14:01 UTC, merged